---
- name: Install basic packages
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - htop
    - iftop
    - powertop
    - mc
    - nano
    - sudo
    - gnupg
    - ntfs-3g
    - rsync
    - screen
    - net-tools
    - anacron
    - sshpass
    - wget
    - curl
    - iptables
    - fail2ban
