---


# ToDo: migrate to 1Password
- name: Retrieve access data
  set_fact:
    user: "{{ secret_values[relationship.user] }}"
    password: "{{ secret_values[relationship.password] }}"
    host: "{{ secret_values[relationship.host] }}"

- name: Create trust relationship
  ansible.builtin.command: sshpass -p '{{ password }}' ssh-copy-id -o StrictHostKeyChecking=no {{ user }}@{{ host }}